###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlbW9uIiwiaWQiOiI2MjExN2UwMDU0ZWZjYzNmOWM0OTMxNjkiLCJpYXQiOjE2NDUzMTY2Njd9.1CNbbrJ8M7m9y47dsj7rAB1cSPhbJDQ6wdM6GyY9yMw   

{
  "title": "here we go again",
  "author": "some guy in tampere",
  "url": "www.google.com",
  "likes": "2"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "remon",
  "name": "doremon",
  "password": "abcdef"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "remon",
  "password": "abcdef"
}