POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "why are you a failure",
  "author": "mr failure",
  "url": "www.google.com",
  "likes": "2"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "remon",
  "name": "doremon",
  "password": "abcdef"
}