POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "hello world",
  "author": "me",
  "url": "www.google.com",
  "likes": "1"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "xax",
  "name": "me",
  "password": "ab"
}